//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Catagory
    {
        public tb_Catagory()
        {
            this.tb_ParamName = new HashSet<tb_ParamName>();
        }
    
        public int ID { get; set; }
        public string CatagoryName { get; set; }
    
        public virtual ICollection<tb_ParamName> tb_ParamName { get; set; }
    }
}
