//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ParamValue
    {
        public int ID { get; set; }
        public Nullable<int> ParamNameID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Val1 { get; set; }
        public string Val2 { get; set; }
        public string Tolerance { get; set; }
        public string Status { get; set; }
    
        public virtual tb_ParamName tb_ParamName { get; set; }
        public virtual tb_Product tb_Product { get; set; }
    }
}
