//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ParamName
    {
        public tb_ParamName()
        {
            this.tb_ParamList = new HashSet<tb_ParamList>();
            this.tb_ParamListValues = new HashSet<tb_ParamListValues>();
            this.tb_ParamValue = new HashSet<tb_ParamValue>();
            this.tb_ValuesOfReport_Lists = new HashSet<tb_ValuesOfReport_Lists>();
            this.tb_ValuesOfReports = new HashSet<tb_ValuesOfReports>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> WireID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Formula { get; set; }
        public Nullable<int> ShowParam { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.TimeSpan> ModifiedTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> CatagoryID { get; set; }
        public Nullable<int> Enable { get; set; }
    
        public virtual tb_Catagory tb_Catagory { get; set; }
        public virtual ICollection<tb_ParamList> tb_ParamList { get; set; }
        public virtual ICollection<tb_ParamListValues> tb_ParamListValues { get; set; }
        public virtual tb_Unit tb_Unit { get; set; }
        public virtual tb_ParamTypes tb_ParamTypes { get; set; }
        public virtual tb_Wirename tb_Wirename { get; set; }
        public virtual ICollection<tb_ParamValue> tb_ParamValue { get; set; }
        public virtual ICollection<tb_ValuesOfReport_Lists> tb_ValuesOfReport_Lists { get; set; }
        public virtual ICollection<tb_ValuesOfReports> tb_ValuesOfReports { get; set; }
    }
}
