//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public tb_Product()
        {
            this.tb_ParamValue = new HashSet<tb_ParamValue>();
            this.tb_Reports = new HashSet<tb_Reports>();
            this.tb_ValuesOfReports = new HashSet<tb_ValuesOfReports>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WirenameID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.TimeSpan> ModifiedTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> Enable { get; set; }
    
        public virtual tb_Degree tb_Degree { get; set; }
        public virtual ICollection<tb_ParamValue> tb_ParamValue { get; set; }
        public virtual tb_Size tb_Size { get; set; }
        public virtual tb_Wirename tb_Wirename { get; set; }
        public virtual ICollection<tb_Reports> tb_Reports { get; set; }
        public virtual ICollection<tb_ValuesOfReports> tb_ValuesOfReports { get; set; }
    }
}
