//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ValuesOfReports
    {
        public tb_ValuesOfReports()
        {
            this.tb_ValuesOfReport_Lists = new HashSet<tb_ValuesOfReport_Lists>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParamNameID { get; set; }
        public Nullable<int> ParamNameListID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Val1 { get; set; }
        public string Val2 { get; set; }
        public string Tolerance { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReportID { get; set; }
    
        public virtual tb_ParamList tb_ParamList { get; set; }
        public virtual tb_ParamName tb_ParamName { get; set; }
        public virtual tb_Product tb_Product { get; set; }
        public virtual tb_Reports tb_Reports { get; set; }
        public virtual ICollection<tb_ValuesOfReport_Lists> tb_ValuesOfReport_Lists { get; set; }
    }
}
