//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WireLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WireTestSoftwareDBEntities : DbContext
    {
        public WireTestSoftwareDBEntities()
            : base("name=WireTestSoftwareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Catagory> tb_Catagory { get; set; }
        public virtual DbSet<tb_Degree> tb_Degree { get; set; }
        public virtual DbSet<tb_Employee> tb_Employee { get; set; }
        public virtual DbSet<tb_ParamList> tb_ParamList { get; set; }
        public virtual DbSet<tb_ParamListValues> tb_ParamListValues { get; set; }
        public virtual DbSet<tb_ParamName> tb_ParamName { get; set; }
        public virtual DbSet<tb_ParamTypes> tb_ParamTypes { get; set; }
        public virtual DbSet<tb_ParamValue> tb_ParamValue { get; set; }
        public virtual DbSet<tb_Product> tb_Product { get; set; }
        public virtual DbSet<tb_Reports> tb_Reports { get; set; }
        public virtual DbSet<tb_Size> tb_Size { get; set; }
        public virtual DbSet<tb_Unit> tb_Unit { get; set; }
        public virtual DbSet<tb_ValuesOfReport_Lists> tb_ValuesOfReport_Lists { get; set; }
        public virtual DbSet<tb_ValuesOfReports> tb_ValuesOfReports { get; set; }
        public virtual DbSet<tb_Wirename> tb_Wirename { get; set; }
    }
}
